name: NCTL Scan Pipeline Demo
run-name: ${{ github.actor }} has triggered Scan Action 🚀
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

env:
  NIRMATA_API_KEY: "B/wYOT9TdTLuqsRS/mNji58e5mWKoJ4MINSzE14pllS0AnsjAqQjAEiNi6Yqz4ICZAqhjtkN6MNwscy3QH2qnw=="
  NIRMATA_URL: "https://staging.nirmata.co"


jobs:
  NCTL-Scan-Dockerfile:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out main repository code
        uses: actions/checkout@v4

      - name: Download and Install nctl
        shell: bash
        run: |
          #!/bin/bash

          shopt -s expand_aliases
          set -e

          # Determine the download URL based on the release version
          #download_url="https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_3.4.4-beta.1/nctl_3.4.4-beta.1_linux_64-bit.zip"
          download_url="https://github.com/nirmata/go-nctl/releases/download/v4.0.0-alpha.3/nctl_4.0.0-alpha.3_linux_amd64.zip"
          curl -L -o nctl.zip $download_url
          unzip -q nctl.zip
          ls -lrt
          chmod +x nctl

      - name: NCTL Scan - Dockerfile
        run: ./nctl scan git-repo --policies ./policy/
  
      - run: echo "🍏 This job's status is ${{ job.status }}."
